### ISSUE TITLE
macat exits after receiving first message

### ISSUE THREAD

**Issue by ekorenevsky** [gdamore/mangos#108]
Steps to reproduce:
./macat --pub --bind=tcp://127.0.0.1:40001 -D test -i 1

./macat --sub --connect=tcp://127.0.0.1:40001 --subscribe=test -A
test
<Exit>

Compare to nanocat:
nanocat --sub --connect=tcp://127.0.0.1:40001 --subscribe=test -A
test
test
test
... runs without exit ...

**Comment by gdamore** [comment]
We need the fix for #110   ... then frankly we should just change the loops in macat to match the same design that nanocat uses.
