### ISSUE TITLE
Add support for priority send/receive

### ISSUE THREAD

**Issue by gdamore** [gdamore/mangos#13]
Originally: https://bitbucket.org/gdamore/mangos/issue/13

We need the ability to use priorities ala SNDPRIO, RCVPRIO.

However:

Its actually unclear whether this is useful. Furthermore, the architecture involving the use of multiple goroutines means that this is impractical without adding a new set of channels and additional latency.
Closing WONTFIX for now. Revisit when/if we ever get a business case.

**Comment by ngConsulti** [comment]
I think the use-case (load balancing/failover) is well described here by the author of nanomsg himself: http://250bpm.com/blog:14

If I find the time, would you be open to a PR?

**Comment by gdamore** [comment]
Sure.  I won't deny that I'm skeptical but if you come up with a nice implementation that doesn't poorly impact the non prioritized cases then I see no reason to turn down a PR.

**Comment by gdamore** [comment]
Btw have you considered using a device to route this for you?  Maybe changes to the core aren't the best way to do this?

**Comment by ngConsulti** [comment]
OK. I'll noodle on it for awhile...

The thing I like about SNDPRIO in particular is that it moves the responsibility for load-balancing and failover to the clients, thereby eliminating a single point of failure in the infrastructure. 

I'm not sure I grok your suggestion to use a device for routing...can you elaborate?
