### ISSUE TITLE
transports don't need read/write locks

### ISSUE THREAD

**Issue by gdamore** [gdamore/mangos#131]
We use locks for read/write on the transports, but it turns out that the various transports are always run single threaded.  Therefore, there is no chance of interleaving.  This actually means that we can save both the lock/unlock for every message sent, but also a defer.

**Comment by tylertreat** [comment]
I should just look at the code, but does this work because the messages get serialized at the upper write queue? Basically multiple "user" threads are writing messages into a channel which is then processed by a single mangos thread?

**Comment by gdamore** [comment]
the reason is that the protocol implementations always fire off a single goroutine to service each transport endpoint.  So there is no chance that there will ever be concurrency to worry about in this case.

**Comment by tylertreat** [comment]
Cool, I imagine this might actually improve performance a fair amount even though there's no lock contention, since it's on every message. And for free! :)
