### ISSUE TITLE
Is there a PAIR like socket but with multiple clients

### ISSUE THREAD

**Issue by wari** [gdamore/mangos#146]
In REQREP, multiple clients can connect to a server, and do requests and waiting for replies, but the requests are only one way (from the client). The PAIR allows the server to send messages to the client to say, query its status, etc. But the connection is exclusive, i.e. I can't have a node1 and node2 in the example code, node2 will keep on sending forever, and node0 has no idea of node2.

I'd like to have PAIR's behaviour, but with multiple clients, or should I use raw instead to get the functionality I want. I do not want to go like the saltstack's way of using 2 sockets for REQREP and REPREQ.

Thanks.

**Comment by gdamore** [comment]
Raw mode pair should work.  The problem with pair is that a for a sender with multiple peers you have to choose which peer to send to.  Then pattern lacks information to choose that. But if you can choose manually in raw mode then it will work. 

But if you have unidirectional messaging maybe pub/sub is better?

I actually think two sockets is indeed the cleanest and best solution.

**Comment by wari** [comment]
I've done something like PAIR with SSL/HTTP/WebSockets as well as gRPC(HTTP2/TLS), with multiple clients connected to a server, once we've properly assigned a connection of a client/server to a connection (usually I keep connection state and information in a map), one can then send messages from server to client or from client to server without mistakenly sending messages to a wrong client.

What I want is bidirectional, just wondering which pattern would best fit my needs.

This use case is particularly useful where,

1. server needs to send messages to clients. 
2. Clients then needs to reply.
3. If at a point of time, client needs some information,
4. it can send a message to a server
5. Receives back a reply.
6. Clients can connect to a server (usually behind a NAT connection)
7. Server has no way to access clients.

If 3 and 4 is not important, I guess a server REQ and client REP type connection will work.

Thanks

**Comment by gdamore** [comment]
Don't forget that you can reverse the role of TCP connect and accept relative to req/rep. 

That said it sounds like you have two sockets.  One with req/rep and another with pub/sub.

**Comment by wari** [comment]
When you say reverse the role, does that mean on the fly? If so, how is that done? Say initial connect will be REQREP, and then switch to REPREQ for all other comms onwards?

**Comment by gdamore** [comment]
Sorry, this got lost in my backlog of email.  By reverse, I mean you can have the REQ do the *accept/listen* rather than the connect side.

I'm closing this issue, as these are just questions and not defects.  Feel free to use gitter or email to reach out directly.
