### ISSUE TITLE
Silent discard of large Recv() messages

### ISSUE THREAD

**Issue by rahulpowar** [gdamore/mangos#150]
I have written a short test to demonstrate this below. Essentially, I was getting timeouts for some large payloads across mangos and it looked like the `Recv()` on a `rep` socket was discarding the message. Digging through the code, we [found this] (https://github.com/gdamore/mangos/blob/774a176919d40f4a5da37f1cb5da5158430b3580/conn.go#L52) which is most likely what we are experiencing and I understand the motivation and the workaround. However:

1. This isn't documented anywhere which should probably be addressed
2. The error does not bubble up and without a `OptionRecvDeadline` hangs the goroutine

```
package tmp_test

import (
	"github.com/gdamore/mangos"
	"github.com/gdamore/mangos/protocol/rep"
	"github.com/gdamore/mangos/protocol/req"
	"github.com/gdamore/mangos/transport/ipc"
	"os"
	"testing"
	"time"
)

const file = "/tmp/mangos-test.sock"
const address = "ipc://" + file
const msg = 5

func runRepReqPair(payloadSize int, t *testing.T) {
	repS, err := rep.NewSocket()
	if err != nil {
		t.Error(err)
		return
	}

	repS.AddTransport(ipc.NewTransport())

	if err = repS.Listen(address); err != nil {
		t.Error(err)
		return
	}

	defer repS.Close()

	reqS, err := req.NewSocket()
	if err != nil {
		t.Error(err)
		return
	}

	reqS.AddTransport(ipc.NewTransport())

	if err = reqS.Dial(address); err != nil {
		t.Error(err)
		return
	}
	defer reqS.Close()
	reqS.SetOption(mangos.OptionRecvDeadline, time.Second*1)

	go func() {
		for i := 0; i < msg; i++ {
			b, err := repS.Recv()
			if err != nil {
				t.Fatal(err)
				break
			}

			t.Logf("REP: Got %d bytes", len(b))

			if err := repS.Send(b); err != nil {
				t.Fatal(err)
				break
			}
		}
	}()

	bys := make([]byte, payloadSize)
	for i := 0; i < msg; i++ {
		reqS.Send(bys)

		b, err := reqS.Recv()
		if err != nil {
			t.Error(err)
			break
		}

		t.Logf("REQ: Got %d bytes back", len(b))
	}
}

func TestByteSend(t *testing.T) {
	os.Remove(file)

	for _, sz := range []int{1024, 100 * 1024, 1024 * 1024} {
		t.Logf("Running @ %d bytes", sz)
		runRepReqPair(sz, t)
	}
}
```

**Comment by gdamore** [comment]
Yep.  I'm not sure about passing the error up.  There could be reasons to do that but I also see reasons not too.  Eg if in a multi peer pattern should one bad peer be able to cause errors up to the local receiver.   Not sure. 

The intent is to make this tunable. As I indicated you can also preallocate the buffers to bypass this limit altogether. 

I'd welcome suggestions as to the doc improvements though.

Ultimately at a protocol level it would be nicer to send this rejection back to the sender.  Some sort of NAK in the wire protocol.  Fixing that requires changing the wire protocol.

**Comment by rahulpowar** [comment]
I had a look and could not figure out how I preallocate this recv buffer. Any pointers?

Alternatively seems like something one could add a SetOption() for, a limit is fine would just need something ~10x the currently hardcoded value for my use case.

**Comment by gdamore** [comment]
Yes there is a plan to have this be an option.  I just hadn't got to it.

**Comment by rahulpowar** [comment]
Ok, what about the current option to preallocate this recv buffer? I can find the code path that will allow me to bypass this check and provide it.

**Comment by gdamore** [comment]
Huh.   I think I never actually implemented that.  The intention was to offer a variant of Recv that allowed the user to supply the inbound buffer.

I'll add code to make the size option settable.

**Comment by gdamore** [comment]
This is really a dup of #31

**Comment by gdamore** [comment]
So #31 is now fixed.  Closing this as a dup.
