### ISSUE TITLE
pubsub: it stops publishing if messages are not consumed

### ISSUE THREAD

**Issue by brunoqc** [gdamore/mangos#163]
I'm not sure if this is an issue. It's possible I don't really understand pub/sub and nanomsg.

If I start the pubsub example as a server with no client, after a while it stops publishing the date until a client connects and receive them.

I was under the impression that if I pub something and there's no client, the data is lost and the client only receive the data published after the connection is made. In that way I guess there's no way to know if a message was lost because of network errors.

**Comment by gdamore** [comment]
What is happening is that messages are backed up in the queue, and when there is no more room, we discard new ones. 

How are you noticing that it 'stops publishing', if there is no client connected?  The client program stops sending messages?

**Comment by brunoqc** [comment]
> How are you noticing that it 'stops publishing', if there is no client connected? The client program stops sending messages?

I was under the impression that the code blocked at [sock.Send()](https://github.com/gdamore/mangos/blob/master/examples/pubsub/pubsub.go#L66) since I stopped seeing "SERVER: PUBLISHING DATE" messages.

I'm curious why there's a queue and that the pub/sub behaves differently than with nanocat:
```sh
nanocat --sub --connect tcp://127.0.0.1:8861 --ascii
nanocat --sub --connect tcp://127.0.0.1:8861 --ascii
```

I also wonder why there's a queue if the new data is discarded when full.

**Comment by gdamore** [comment]
Why'd you close this?
