### ISSUE TITLE
pubsub: messages aren't always received

### ISSUE THREAD

**Issue by dwlnetnl** [gdamore/mangos#164]
It seems that mangos SUB sockets behave not the same as nn_sub sockets.
- When I have only a single mangos SUB socket connected to a PUB, it works.
- When I connected multiple mangos SUB sockets, only the first SUB gets messages.
- When I connect one or more nn_sub sockets (nanocat), all of those get the messages.

This might be the same issue as reported in the last comment of #163.

**Comment by dwlnetnl** [comment]
Maybe this behaviour has to do with starting the subscribers before the publisher.

**Comment by dwlnetnl** [comment]
The strange thing for me is that it doesn't work (mangos) when I start the PUB literally after the SUBs. But I will look with Wireshark to diagnose the problem in more detail.

**Comment by gdamore** [comment]
You still have to wait for the TCP sessions to establish.  The minimum wait time is 100 msec if you start the SUBs (which are normally the Dialers) first.  Probably you should wait more like 200-500 msec.

**Comment by dwlnetnl** [comment]
I've looked to the nanomsg source and indeed the minimum wait is by default 100 ms, but the maximum wait is 0. In mangos the maximum wait is 1 second. Personally I'd like to see values in the 2 implementations to minimise surprises.

But when I change the maximum wait to time.Duration(0), the reconnect packets seem to be buffered.
If you'd like I can supply pcap files.

**Comment by dwlnetnl** [comment]
The pull request is a rough source change. Docs are not changed and the option to change ```NN_RECONNECT_IVL``` and ```NN_RECONNECT_IVL_MAX``` isn't there. No problem add that.

**Comment by gdamore** [comment]
So, with the new behavior, addressing the TCP slow start problem, do you still have problems with pub/sub receiving messages?  If not, let's close this bug.

**Comment by dwlnetnl** [comment]
No I don't have any problems anymore. Thanks for the additional coding of the options, great!
