### ISSUE TITLE
question: fan out

### ISSUE THREAD

**Issue by joeblew99** [gdamore/mangos#167]
I a wondering if mango provide fan out ?
this is when the producer, sends the message out ot many consumers, with each consumer getting only one of the original messages.
Its a bit like what a load balancer does in round robin sequence.

**Comment by gdamore** [comment]
Like a load balancer.  We do have a dumb form of this in the req code where we choose one of several destinations. The algorithm used is fairly dumb so it's not well suited to making sophisticated decisions based on queuing or topology etc. 

The other patterns lack this.  Only req sockets have this sort of single destination selection as its kind of nonsensical to do so for other socket types.
