### ISSUE TITLE
Connecting to multiple surveyor sockets

### ISSUE THREAD

**Issue by tylertreat** [gdamore/mangos#25]
Is it possible for a respondent to connect to more than one surveyor socket? E.g.

```go
respondent, _ := respondent.NewSocket()
respondent.AddTransport(tcp.NewTransport())
respondent.Dial("tcp://127.0.0.1:5000")
respondent.Dial("tcp://127.0.0.1:5001")
```

The current behavior seems to be undefined. With the above code, surveys are always received from either the first or second but not both. If surveys can't be received from multiple sockets, I'd expect the behavior to be consistent when trying to connect to multiple sockets. Either:

1. Return error when trying to connect when already connected to surveyor
2. Receive surveys from the first-made connection
3. Receive surveys from the last-made connection

Thoughts?

**Comment by gdamore** [comment]
Btw, this is now done in nanomsg (see my mail yesterday).  I've got a mangos implementation that works too.  Will post it here momentarily.  Ideally I'd like to push the two things together, so that both libraries stayed in sync.
