### ISSUE TITLE
routing and device with pub socket

### ISSUE THREAD

**Issue by trihatmaja** [gdamore/mangos#42]
Hi Guys, Another noobs here. I want to ask something.

1. Suppose i got 2 worker behind a device, worker 'a' and 'b'. The requester want to send msg to worker 'a'. If i do this on micro controller, i send the msg to all worker, but only worker that being specified from the sender respond it, the other just throw the msg. If i do this using zmq, i got some socket id option so that i send it to that ID. When i use nanomsg, i'm thinking about the bus socket but how i can do it?

2. Can i see what the message that going through or even stuck in the socket? Or using some proxy device/monitoring device/forwarder with pub socket?

**Comment by gdamore** [comment]
You can write a "custom" device to do this.  You need to put the sockets in Raw mode, but then you can see headers, and of course the contents as well, and selectively forward in your custom device implementation.  You can look in device.go to see the trivial non-filtering device implementation I created.  You'll need to do some more meaty work, and want to support more than one socket on each side.

To introspect inside the sockets themselves, you'd need to modify the code.   There are actually hooks for that, but I consider this internal implementation to mangos, and subject to change without notice.  (These hooks are used in the implementation of the actual protocols, themselves.)

**Comment by trihatmaja** [comment]
I see.. thx..
