### ISSUE TITLE
inproc accept logic convoluted, and prone to deadlock

### ISSUE THREAD

**Issue by gdamore** [gdamore/mangos#47]
The whole rendezvous logic in the inproc implementation is far too byzantine, making use of go channels and go routines to distraction.  Ultimately, there was a deadlock there, I'm pretty sure.  This can be greatly simplified.

**Comment by rzezeski** [comment]
The device_test still deadlocks on the inproc branch, but I don't see inproc involved like previous stack dumps. I'm going to keep running to check for different stacks.

```
    rpz@ubuntu:~/gowrk/src/github.com/gdamore/mangos/test$ git status
    On branch inproc
    Your branch is up-to-date with 'origin/inproc'.

    nothing to commit, working directory clean

    rpz@ubuntu:~/gowrk/src/github.com/gdamore/mangos/test$ ~/repeat.sh 20 device_test.go common_test.go tls_test.go
    ok      command-line-arguments  2.876s
    time: Fri Jan 23 15:20:53 EST 2015
    ok      command-line-arguments  3.694s
    time: Fri Jan 23 15:20:57 EST 2015
    ok      command-line-arguments  2.819s
    time: Fri Jan 23 15:21:01 EST 2015
    ok      command-line-arguments  2.940s
    time: Fri Jan 23 15:21:05 EST 2015
    ok      command-line-arguments  2.905s
    time: Fri Jan 23 15:21:09 EST 2015

    SIGABRT: abort
    PC=0x441523

    goroutine 6 [syscall]:
    runtime.notetsleepg(0x1279058, 0x5f5d808, 0x16)
        /usr/local/go/src/runtime/lock_futex.go:201 +0x52 fp=0xc208020760 sp=0xc208020738
    runtime.timerproc()
        /usr/local/go/src/runtime/time.go:207 +0xfa fp=0xc2080207e0 sp=0xc208020760
    runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080207e8 sp=0xc2080207e0
    created by runtime.addtimerLocked
        /usr/local/go/src/runtime/time.go:113 +0x1ba

    goroutine 1 [chan receive, 2 minutes]:
    testing.RunTests(0x7fc960, 0x1276f00, 0xc, 0xc, 0x1)
        /usr/local/go/src/testing/testing.go:556 +0xdc3
    testing.(*M).Run(0xc2080780a0, 0x1280c80)
        /usr/local/go/src/testing/testing.go:485 +0xe1
    main.main()
        command-line-arguments/_test/_testmain.go:74 +0x28d

    goroutine 33 [select]:
    github.com/gdamore/mangos.(*socket).Close(0xc2080e2000, 0x0, 0x0)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/core.go:153 +0x60e
    command-line-arguments.testDevChain(0xc2080de000, 0x7a76b0, 0x15, 0x7a2d70, 0x15, 0x7a27b0, 0x16)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/test/device_test.go:268 +0x16ac
    command-line-arguments.TestDeviceChain(0xc2080de000)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/test/device_test.go:271 +0xae
    testing.tRunner(0xc2080de000, 0x1276f90)
        /usr/local/go/src/testing/testing.go:447 +0x134
    created by testing.RunTests
        /usr/local/go/src/testing/testing.go:555 +0xd4e

    goroutine 50 [select, 1 minutes]:
    github.com/gdamore/mangos/protocol/pair.(*pair).sender(0xc2080e0870, 0x7f57f7e18cc8, 0xc208062500)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:40 +0x1c2
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:77 +0x13b

    goroutine 22 [select, 2 minutes]:
    github.com/gdamore/mangos/protocol/rep.(*rep).sender(0xc2080ba5a0)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/rep/rep.go:103 +0x52b
    created by github.com/gdamore/mangos/protocol/rep.(*rep).Init
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/rep/rep.go:47 +0x164

    goroutine 66 [select, 1 minutes]:
    github.com/gdamore/mangos/protocol/pair.(*pair).sender(0xc2080e0e10, 0x7f57f7e18cc8, 0xc208108000)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:40 +0x1c2
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:77 +0x13b

    goroutine 35 [select, 1 minutes]:
    github.com/gdamore/mangos/protocol/pair.(*pair).sender(0xc2080c8c30, 0x7f57f7e18cc8, 0xc2080bc000)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:40 +0x1c2
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:77 +0x13b

    goroutine 26 [select, 1 minutes]:
    github.com/gdamore/mangos/protocol/pair.(*pair).sender(0xc2080e0270, 0x7f57f7e18cc8, 0xc2080b2140)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:40 +0x1c2
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:77 +0x13b

    goroutine 38 [select, 1 minutes]:
    github.com/gdamore/mangos/protocol/pair.(*pair).sender(0xc2080c8a20, 0x7f57f7e18cc8, 0xc2080b4100)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:40 +0x1c2
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:77 +0x13b

    rax     0xfffffffffffffffc
    rbx     0x5f5d808
    rcx     0xffffffffffffffff
    rdx     0x0
    rdi     0x1279058
    rsi     0x0
    rbp     0xc2080206f8
    rsp     0xc2080206b8
    r8      0x0
    r9      0x0
    r10     0xc2080206f0
    r11     0x206
    r12     0xc20808cba8
    r13     0x12798a0
    r14     0xc20804efc0
    r15     0x7f57f7dfbe10
    rip     0x441523
    rflags  0x206
    cs      0x33
    fs      0x0
    gs      0x0
    FAIL    command-line-arguments  175.633s
```

**Comment by rzezeski** [comment]
Another deadlock, slightly different stacks, this one has one goroutine stuck on a semacquire.


    SIGABRT: abort
    PC=0x441521

    goroutine 0 [idle]:
    runtime.futex(0x1279978, 0x0, 0x0, 0x0, 0x0, 0x1279320, 0x1, 0x40d12f, 0x40d34e, 0x1279978, ...)
        /usr/local/go/src/runtime/sys_linux_amd64.s:277 +0x21
    runtime.futexsleep(0x1279978, 0x0, 0xffffffffffffffff)
        /usr/local/go/src/runtime/os_linux.c:49 +0x47
    runtime.notesleep(0x1279978)
        /usr/local/go/src/runtime/lock_futex.go:145 +0xae
    stopm()
        /usr/local/go/src/runtime/proc.c:1178 +0x119
    findrunnable(0xc208012900)
        /usr/local/go/src/runtime/proc.c:1487 +0x562
    schedule()
        /usr/local/go/src/runtime/proc.c:1575 +0x151
    goexit0(0xc208001b00)
        /usr/local/go/src/runtime/proc.c:1717 +0x16e
    runtime.mcall(0x433d64)
        /usr/local/go/src/runtime/asm_amd64.s:186 +0x5a

    goroutine 1 [chan receive]:
    testing.RunTests(0x7fc960, 0x1276f00, 0xc, 0xc, 0x1)
        /usr/local/go/src/testing/testing.go:556 +0xdc3
    testing.(*M).Run(0xc2080780a0, 0x1280c80)
        /usr/local/go/src/testing/testing.go:485 +0xe1
    main.main()
        command-line-arguments/_test/_testmain.go:74 +0x28d

    goroutine 14 [select]:
    github.com/gdamore/mangos/protocol/rep.(*rep).sender(0xc20807f380)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/rep/rep.go:103 +0x52b
    created by github.com/gdamore/mangos/protocol/rep.(*rep).Init
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/rep/rep.go:47 +0x164

    goroutine 33 [select]:
    github.com/gdamore/mangos.(*socket).Close(0xc2080a2620, 0x0, 0x0)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/core.go:153 +0x60e
    command-line-arguments.testDevChain(0xc208066240, 0x7a76b0, 0x15, 0x7a2d70, 0x15, 0x7a27b0, 0x16)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/test/device_test.go:268 +0x16ac
    command-line-arguments.TestDeviceChain(0xc208066240)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/test/device_test.go:271 +0xae
    testing.tRunner(0xc208066240, 0x1276f90)
        /usr/local/go/src/testing/testing.go:447 +0x134
    created by testing.RunTests
        /usr/local/go/src/testing/testing.go:555 +0xd4e

    goroutine 20 [select]:
    github.com/gdamore/mangos/protocol/pair.(*pair).sender(0xc2080d89f0, 0x7f92e6a17c50, 0xc2080dc2c0)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:40 +0x1c2
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:77 +0x13b

    goroutine 50 [select]:
    github.com/gdamore/mangos/protocol/pair.(*pair).sender(0xc2080d9080, 0x7f92e6a17c50, 0xc2080a6000)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:40 +0x1c2
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:77 +0x13b

    goroutine 65 [semacquire]:
    sync.(*Mutex).Lock(0xc2080a6274)
        /usr/local/go/src/sync/mutex.go:66 +0xfd
    github.com/gdamore/mangos.(*pipe).Close(0xc2080a6240, 0x0, 0x0)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/pipe.go:73 +0x58
    github.com/gdamore/mangos.(*pipe).RecvMsg(0xc2080a6240, 0xc20807e900)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/pipe.go:102 +0x89
    github.com/gdamore/mangos/protocol/pair.(*pair).receiver(0xc2080d9140, 0x7f92e6a17c50, 0xc2080a6240)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:55 +0x4d
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:76 +0x10d

    goroutine 22 [select]:
    github.com/gdamore/mangos/protocol/pair.(*pair).sender(0xc2080d8e70, 0x7f92e6a17c50, 0xc2080dc740)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:40 +0x1c2
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:77 +0x13b

    goroutine 24 [select]:
    github.com/gdamore/mangos/protocol/pair.(*pair).sender(0xc2080d8e10, 0x7f92e6a17c50, 0xc2080dc7c0)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:40 +0x1c2
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:77 +0x13b

    rax     0xca
    rbx     0x1279978
    rcx     0xffffffffffffffff
    rdx     0x0
    rdi     0x1279978
    rsi     0x0
    rbp     0x1
    rsp     0x7fff4a6f41f8
    r8      0x0
    r9      0x0
    r10     0x0
    r11     0x286
    r12     0xc20801f788
    r13     0x12798a0
    r14     0xc208001b00
    r15     0x383a60f8
    rip     0x441521
    rflags  0x286
    cs      0x33
    fs      0x0
    gs      0x0
    FAIL    command-line-arguments  55.207s

**Comment by rzezeski** [comment]
As Garrett discovered the break statement in `Close()` applies to the select, not the for. After fixing this I have not been able to hit a deadlock in over 100 runs (normally I can hit it 1 in 10 times).

https://github.com/gdamore/mangos/blob/master/core.go#L155
