### ISSUE TITLE
Add websocket support

### ISSUE THREAD

**Issue by gdamore** [gdamore/mangos#62]
Websocket transport following the nanomsg RFC.

**Comment by tylertreat** [comment]
Is that RFC in progress?

**Comment by gdamore** [comment]
Yes.  Kind of.

**Comment by gdamore** [comment]
So, I've written a test version of websocket support, but it does not follow the RFC for nanomsg.  In particular, I think that using the x-nanomsg-xxx values to convey the subprotocols used is an impedance mismatch.  Instead I've invented a new handshake which is much much closer to the TCP and IPC handshake methods, but modified to make pass text instead of binary values -- as some web browser clients probably cannot cope with binary values.

I'm going to update nanomsg to use my encoding as well, then I'll post diffs.  The mangos implementation is in the websocket branch which I've pushed.
